#!/bin/bash

. /usrdata/quecdeck/www/cgi-bin/cgi-lib.sh
cgi_check_cors
cgi_require_post

cgi_output_text

cache_get_or_fetch "$_CACHE_SETTINGS" 5 \
    'AT+QMAP="DHCPV4DNS";+QMAP="DHCPV6DNS";+QMAPWAC?;+QGPS?' \
    '+QMAP: "DHCPV4DNS"' '+QMAP: "DHCPV6DNS"' '+QMAPWAC:' '+QGPS:'
