#!/bin/bash

. /usrdata/quecdeck/www/cgi-bin/cgi-lib.sh
cgi_check_cors
cgi_require_post

cgi_output_text

# SIM-dependent: will error if no SIM; caller handles absent fields gracefully.
cache_get_or_fetch "$_CACHE_DEVICE_SIM" 5 'AT+CIMI;+ICCID;+CNUM' 2000
