#!/bin/bash

. /usrdata/quecdeck/www/cgi-bin/cgi-lib.sh
cgi_check_cors
cgi_require_post

cgi_output_text

cache_get_or_fetch "$_CACHE_MODEM_ALL" 3 \
    'AT+QTEMP;+QENG="servingcell";+QCAINFO;+CSQ;+QGDNRCNT?;+QGDCNT?;+QUIMSLOT?;+QSPN;+CGCONTRDP=1;+QMAP="WWANIP";+QSIMSTAT?' \
    '+QENG: "servingcell"' '+CSQ:' '+QUIMSLOT:'
