#!/bin/bash

. /usrdata/quecdeck/www/cgi-bin/cgi-lib.sh
cgi_check_cors
cgi_require_post
cgi_read_post

x=$(get_post_param atcmd)

if [ -n "$x" ] && [ ${#x} -le 512 ]; then
    runcmd=$(atcmd_run "$x")
fi

cgi_output_text
echo "$runcmd"
