#!/bin/bash

. /usrdata/quecdeck/script/cgi-lib.sh
cgi_check_cors
cgi_output_json

if [ -s /usrdata/quecdeck/var/watchcat.json ]; then
    cat /usrdata/quecdeck/var/watchcat.json
else
    ps | grep -q '[w]atchcat.sh' && active="true" || active="false"
    echo "{\"enabled\": $active}"
fi
