#!/bin/bash

. /usrdata/quecdeck/www/cgi-bin/cgi-lib.sh
cgi_check_cors
cgi_require_post

cgi_output_text

cache_get_or_fetch "$_CACHE_DEVICE_INFO" 5 \
    'AT+CGMI;+CGMM;+QGMR;+CIMI;+ICCID;+CGSN;+QMAP="WWAN";+CNUM;+CVERSION;+CGCONTRDP'
