#!/bin/bash

while true; do
    echo -e "\e[1;31mPlease set your developer access (User: devadmin) web login password.\e[0m"
    read -r -s -p "Password: " pw1; echo
    read -r -s -p "Confirm password: " pw2; echo
    if [ "$pw1" = "$pw2" ] && [ "${#pw1}" -ge 8 ]; then
        echo "devadmin:$(printf '%s' "$pw1" | openssl passwd -6 -stdin)" > /opt/etc/.htpasswd_dev
        chown root:dialout /opt/etc/.htpasswd_dev
        chmod 640 /opt/etc/.htpasswd_dev
        echo -e "\e[1;32mDeveloper password set.\e[0m"
        break
    elif [ "$pw1" != "$pw2" ]; then
        echo -e "\e[1;31mPasswords did not match. Please try again.\e[0m"
    else
        echo -e "\e[1;31mPassword must be at least 8 characters. Please try again.\e[0m"
    fi
done
