#!/bin/bash
# Regenerates quecdeck/www/js/network-names.js from Wikipedia's MNC list pages.
# Dev tool, runs on the dev machine (needs curl + perl), not deployed to the device.
#
# Usage:
#   tools/generate-network-names.sh            # fetch pages and regenerate
#   tools/generate-network-names.sh <dir>      # reuse previously fetched *.wiki files in <dir>
#
# Row rules:
# - key = MCC concatenated with MNC as printed (leading zeros kept), matching
#   scanner.js's string-concat lookup (mcc + mnc from the QSCAN response).
# - name = Brand column, falling back to Operator when Brand is empty/unknown.
# - rows with status "Not operational", "Reserved", "Returned spare",
#   "Allocated", "Withdrawn" or "Terminated" are skipped; Operational/Unknown/
#   blank are kept (a scanned cell is on the air, but Wikipedia status lags).
# - duplicate keys: first occurrence wins, later ones are reported on stderr.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/quecdeck/www/js/network-names.js"
UA="QuecDeck-network-names-generator/1.0 (https://github.com/megakerw/QuecDeck)"

PAGES=(
    "Mobile_network_codes_in_ITU_region_2xx_(Europe)"
    "Mobile_network_codes_in_ITU_region_3xx_(North_America)"
    "Mobile_network_codes_in_ITU_region_4xx_(Asia)"
    "Mobile_network_codes_in_ITU_region_5xx_(Oceania)"
    "Mobile_network_codes_in_ITU_region_6xx_(Africa)"
    "Mobile_network_codes_in_ITU_region_7xx_(South_America)"
    "Mobile_country_code"
)

if [ -n "${1:-}" ]; then
    SRC_DIR="$1"
else
    SRC_DIR="$(mktemp -d)"
    trap 'rm -rf "$SRC_DIR"' EXIT
    for page in "${PAGES[@]}"; do
        echo "Fetching $page..." >&2
        curl -sf -A "$UA" \
            "https://en.wikipedia.org/w/index.php?title=${page}&action=raw" \
            -o "$SRC_DIR/${page//[^A-Za-z0-9]/_}.wiki" \
            || { echo "FATAL: failed to fetch $page" >&2; exit 1; }
    done
fi

GEN_DATE="$(date +%Y-%m-%d)"

perl - "$GEN_DATE" "$SRC_DIR"/*.wiki > "$OUT" <<'PERL'
use strict; use warnings;
my $gen_date = shift @ARGV;

# Strip wiki markup from one table cell, leaving display text.
sub clean {
    my ($s) = @_;
    return '' unless defined $s;
    $s =~ s/<ref[^>]*\/>//g;              # self-closing refs
    $s =~ s/<ref[^>]*>.*?<\/ref>//gs;     # ref bodies
    1 while $s =~ s/\{\{[^{}]*\}\}//g;    # templates, innermost first
    $s =~ s/\[\[[^\]|]*\|([^\]]*)\]\]/$1/g;   # [[target|label]] -> label
    $s =~ s/\[\[([^\]]*)\]\]/$1/g;            # [[target]] -> target
    $s =~ s/\[\S+\s+([^\]]*)\]/$1/g;          # [url label] -> label
    $s =~ s/<[^>]+>//g;                   # html tags
    $s =~ s/'{2,}//g;                     # bold/italic quotes
    $s =~ s/&nbsp;/ /g; $s =~ s/&amp;/&/g;
    $s =~ s/\s+/ /g; $s =~ s/^\s+|\s+$//g;
    return $s;
}

my (%names, @order, $dupes, $rows);
my @cells;

sub flush_row {
    my @c = map { clean($_) } @cells;
    @cells = ();
    return if @c < 4;
    my ($mcc, $mnc, $brand, $operator, $status) = @c;
    return unless defined $mcc && $mcc =~ /^\d{3}$/;
    return unless defined $mnc && $mnc =~ /^\d{2,3}$/;
    $status //= '';
    return if $status =~ /not operational|reserved|returned|allocated|withdrawn|terminated/i;
    my $name = $brand;
    $name = $operator if !defined($name) || $name eq '' || $name =~ /^(\?+|-|unknown)$/i;
    return if !defined($name) || $name eq '' || $name =~ /^(\?+|-|unknown)$/i;
    $name =~ s/\\/\\\\/g; $name =~ s/"/\\"/g;
    my $key = $mcc . $mnc;
    if (exists $names{$key}) {
        print STDERR "dupe: $key kept \"$names{$key}\" dropped \"$name\"\n" if $names{$key} ne $name;
        $dupes++;
        return;
    }
    $names{$key} = $name;
    push @order, $key;
    $rows++;
}

while (<>) {
    chomp;
    if (/^\|\}/ or /^\|-/) { flush_row(); next; }
    next if /^!/ or /^\|\+/;
    if (/^\|(.*)$/) {
        push @cells, split /\s*\|\|\s*/, $1, -1;
    }
}
flush_row();

die "parsed suspiciously few rows ($rows), aborting\n" if $rows < 1500;

print "// MCC+MNC to operator name lookup, used by scanner.js. Data only.\n";
print "// Generated by tools/generate-network-names.sh from Wikipedia's\n";
print "// \"Mobile network codes in ITU region ...\" pages on $gen_date.\n";
print "// Do not edit by hand; rerun the generator to refresh.\n";
print "const NETWORK_NAMES = {\n";
for my $key (sort { $a <=> $b } @order) {
    print "  \"$key\": \"$names{$key}\",\n";
}
print "};\n";
print STDERR "wrote $rows entries" . ($dupes ? " ($dupes duplicate keys skipped)" : "") . "\n";
PERL

echo "Generated $OUT" >&2
